from dataclasses import dataclass
from typing import Protocol

from app.interface.media import MediaPort


@dataclass(frozen=True)
class AppState:
    fps: int
    cur_frame: int
    total_frames: int
    playing: bool
    error_frames: tuple[int, ...]
    current_folder: str | None


class DanceTrackerPort(Protocol):
    media: MediaPort

    def get_state(self) -> AppState: ...

    def emit_state(self) -> None: ...

    def play(self) -> None: ...

    def pause(self) -> None: ...

    def toggle_playback(self) -> None: ...

    def advance_playback(self) -> None: ...

    def step(self, delta: int) -> None: ...

    def go_to_start(self) -> None: ...

    def go_to_end(self) -> None: ...

    def next_error(self) -> None: ...

    def prev_error(self) -> None: ...

    def set_frame(self, frame: int) -> None: ...

    def set_total_frames(self, total_frames: int) -> None: ...

    def set_current_folder(self, folder_path: str | None) -> None: ...
